version: "2"

services:
    mysql:
        image: mysql
        ports:
              - "3306:3306"
        volumes:
              - /misdatos/mysql:/var/lib/mysql
        environment:
              MYSQL_USER: root
              MYSQL_PASSWORD: secret
              MYSQL_DATABASE: clinica
              MYSQL_ROOT_PASSWORD: secret
    web:
        build: .
        ports: 
            - 8080:80
        volumes: 
            - ./:/opt/data
        depends_on:
            - mysql
